package com.example.wifisignallogger.data.model

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Entity class representing a Location where WiFi readings are collected.
 * Each Location has a unique ID, a name, and a timestamp of when it was created.
 */
@Entity(tableName = "locations")
data class Location(
    /**
     * Primary key for the Location.
     * Auto-generated by the Room database.
     */
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    /**
     * Name given to the Location (e.g., "Library", "Room A", etc.).
     */
    val name: String,

    /**
     * Timestamp indicating when the Location was recorded.
     * Defaults to the current system time at creation.
     */
    val timestamp: Long = System.currentTimeMillis()
)
